language: scala
scala:
  - 2.11.4
jdk:
  - oraclejdk8
  - openjdk7
  - oraclejdk7
install: /bin/true # always succeeds
script:
  - sudo cat /proc/cpuinfo
  - sudo cat /proc/meminfo
  - mvn -B -DskipTests test
  - mvn -B -Dbenchmark.executorServiceType=akka-forkjoin-pool test -Ptravis
  - mvn -B -Dbenchmark.executorServiceType=scala-forkjoin-pool test -Ptravis
  - mvn -B -Dbenchmark.executorServiceType=java-forkjoin-pool test -Ptravis
  - mvn -B -Dbenchmark.executorServiceType=abq-thread-pool test -Ptravis
  - mvn -B -Dbenchmark.executorServiceType=lbq-thread-pool test -Ptravis

